require("mayyar.plugins-setup") --should be always at the top
require("mayyar.core.options")
require("mayyar.core.colorscheme")
require("mayyar.core.keymaps")
require("mayyar.plugins.comment")
require("mayyar.plugins.nvim-tree")
require("mayyar.plugins.lualine")
require("mayyar.plugins.telescope")
require("mayyar.plugins.nvim-cmp")
require("mayyar.plugins.lsp.mason")
require("mayyar.plugins.lsp.lspconfig")
require("mayyar.plugins.lsp.lspsaga")
require("mayyar.plugins.lsp.null-ls")
require("mayyar.plugins.autopairs")
require("mayyar.plugins.treesitter")
